### ISSUE TITLE
USER STORY: Install Django and supporting libraries

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/travelogue#1]
As a **Developer** I can **set up Django and install the initial supporting libraries** so that **I am ready to start development**

## Acceptance Criteria
* Criteria 1
**Given** that this is a new project
**When** users can  share information through the app
**Then** use Django framework to create this project

## Tasks
- [x] Task 1 – Install Django and gunicorn
- [x] Task 2 – Install dj_database_url psycopg2
- [x] Task 3 – Install dj3-cloudinary-storage
- [x] Task 4 – Create a requirements.txt file

## EPIC
1. #38
