### ISSUE TITLE
USER STORY: Delete own account

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/travelogue#10]
As a **Site User** I can **delete my account** so that **I can leave the site permanently**

## Acceptance Criteria
* Criteria 1
**Given** that I am in my account profile
**When** I want to delete my account
**Then** an option is available to delete my account

* Criteria 2
**Given** that I want to delete my account
**When** I click 'Delete'
**Then** it should ask for confirmation before commit delete account

## Tasks
- [x] Task 1 – Develop process to allow users to delete account
- [x] Task 2 – Create Delete button to allow delete account
- [x] Task 3 – Delete account after confirmation

## EPIC
1. #39
