### ISSUE TITLE
USER STORY: Change password

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/travelogue#11]
As a **Site User** I can **change my password** so that **I can secure my account**

## Acceptance Criteria
* Criteria 1
**Given** that I am in my account profile
**When** I want to change my password
**Then** an option is available to change my current password

* Criteria 2
**Given** that I want to change my current password
**When** I submit my current and new passwords
**Then** it should validate the passwords before it allows to commit the changes

## Tasks
- [x] Task 1 – Develop process to allow users to change password
- [x] Task 2 – Create Update Password button to allow changes
- [x] Task 3 – Validate changes before update is allowed

## EPIC
1. #39
