### ISSUE TITLE
USER STORY: Reset password

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/travelogue#12]
As a **Site User** I can **request to reset my password** so that **I can login to my account after forgotten my password**

## Acceptance Criteria
* Criteria 1
**Given** that I want to login to my account
**When** I forgot my password
**Then** an option is available to reset my password

* Criteria 2
**Given** that I forgot my password
**When** I submit my email address and request to reset my password
**Then** the system sends an email with a temporary password to the address provided

## Tasks
- [ ] Task 1 – Develop process to allow users to reset password
- [ ] Task 2 – Create Reset Password button to allow reset
- [ ] Task 3 – User submit account email address
- [ ] Task 4 – Email new password

## EPIC
1. #40
