### ISSUE TITLE
USER STORY: User owner login

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/travelogue#13]
As a **Site User** I can **login to the site** so that **I can create, update and delete my posts with restriction**

## Acceptance Criteria
* Criteria 1
**Given** that I want to login to the site
**When** I submit my details on the login page
**Then** the system will validate the details

* Criteria 2
**Given** that I have submitted my details on the login page
**When** the  details failed on validation
**Then** the system alerts me with invalid login message

* Criteria 3
**Given** that I have submitted my details on the login page
**When** the  details have successfully validated
**Then** the system grant me restricted access to the site but allows me to create, update and delete my posts as well as commenting posts from other users

## Tasks
- [x] Task 1 – Develop process to allow users to login
- [x] Task 2 – Create Login button on navigation bar
- [x] Task 3 – Create login form
- [x] Task 4 – Validate and response to login details
- [x] Task 5 – Login to the system and grant appropriate access

## EPIC
1. #40
