### ISSUE TITLE
USER STORY: Account logout

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/travelogue#15]
As a **Site User/Admin** I can **logout the site** so that **I can protect my posts**

## Acceptance Criteria
* Criteria 1
**Given** that I have login to the site
**When** I want to logout from the site
**Then** an option is available on the navigation bar that allows me to logout

* Criteria 2
**Given** that I want to logout from the site
**When** I click 'Logout' from the navigation bar
**Then** I get a message saying that I have successfully logged out

## Tasks
- [x] Task 1 – Develop process to allow users to logout
- [x] Task 2 – Create Logout button on navigation bar
- [x] Task 3 – Logout and return to home page

## EPIC
1. #40
