### ISSUE TITLE
USER STORY: Create a new blank Django project and apps

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/travelogue#2]
As a **Developer** I can **create a new project and initial app** so that **I have an empty working app**

## Acceptance Criteria
* Criteria 1
**Given** that this will be a Django project
**When** apps can be created
**Then** we can create the first app to test the server

## Tasks
- [x] Task 1 – Create the Django project – called travelogue22kw
- [x] Task 2 – Create the first app – called blog and add it to the installed apps in the settings.py
- [x] Task 3 – Migrate Changes
- [x] Task 4 – Run Server to Test

## EPIC
1. #38
