### ISSUE TITLE
USER STORY: View posts

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/travelogue#21]
As a **Site User** I can **view the list of posts** so that **I can read the posts**

## Acceptance Criteria
* Criteria 1
**Given** that any user on the site
**When** they click a post from the list
**Then** the system allows them to view the selected post

## Tasks
- [x] Task 1 – Create basic page to display posts
- [x] Task 2 – Create basic page to display individual post
- [x] Task 3 - Complete and style pages

## EPIC
1. #43
