### ISSUE TITLE
USER STORY: Add a new post

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/travelogue#24]
As a **Registered Site User** I can **submit a new post** so that **my post can be viewed by other users**

## Acceptance Criteria
* Criteria 1
**Given** that I have an account
**When** I have signed into my account
**Then** options are available in the navigation bar for create, edit and delete my post

* Criteria 2
**Given** that I am on the page of posts
**When** I click 'New Post' on the navigation bar
**Then** I can create a new post

## Tasks
- [x] Task 1 – Create New Post button on navigation bar
- [x] Task 2 – Load page to add new post
- [x] Task 3 – Display new post after submitted

## EPIC
1. #43
