### ISSUE TITLE
USER STORY: Comment on a post

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/travelogue#25]
As a **Registered Site User** I can **click on a post to leave comments** so that **I can join the conservation about the post**

## Acceptance Criteria
* Criteria 1
**Given** that I have an account
**When** I have signed into my account
**Then** it allows me to comment to any posts

* Criteria 2
**Given** that I am on a post
**When** I submit my comment
**Then** I can leave the comment for the post

## Tasks
Use Crispy forms library for formatting
- [x] Task 1 – Create Comment form for the post
- [x] Task 2 – Check user authentication 
- [x] Task 3 – Add new comment for approval to the conversation
- [x] Task 4 - Superuser do not require approval

## EPIC
1. #43
