### ISSUE TITLE
USER STORY: Like or unlike a post

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/travelogue#26]
As a **Registered Site User** I can **click on a post** so that **I can like or unlike the post**

## Acceptance Criteria
* Criteria 1
**Given** that I have an account
**When** I have signed into my account
**Then** it allows me to like or unlike posts

* Criteria 2
**Given** that I am on a post
**When** I click the like icon
**Then** it toggle between like and unlike as well as updating the counter

## Tasks
- [x] Task 1 – Create Like button for the post
- [x] Task 2 – Toggle between like/unlike when clicked
- [x] Task 3 – Update total likes

## EPIC
1. #43
