### ISSUE TITLE
USER STORY: Delete my post

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/travelogue#28]
As a **Registered Site User** I can **select one of my post** so that **I can delete my post from the list**

## Acceptance Criteria
* Criteria 1
**Given** that I have an account
**When** I have signed into my account
**Then** it only allows me to delete my own posts

* Criteria 2
**Given** that I am on one of my post
**When** I click delete
**Then** confirmation is required before deleting the post

## Tasks
- [x] Task 1 – Create Delete button for the post
- [x] Task 2 – Display button only to the post owner
- [x] Task 3 – Confirm and delete post from the system

## EPIC
1. #43
