### ISSUE TITLE
USER STORY: Set project to use Cloudinary and PostgreSQL in Heroku

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/travelogue#3]
As a **Developer** I can **setup Cloudinary and PostgreSQL** so that **the users can store images and data online**

## Acceptance Criteria
* Criteria 1
**Given** that the apps use images and store data
**When** posts can be viewed, added, edited and deleted from the site
**Then** Cloudinary and PostgreSQL will be used and deploy in Heroku

## Tasks
- [x] Task 1 – Create the Heroku app
- [x] Task 2 – Attach the PostgeSQL database
- [x] Task 3 – Prepare environment and setting.py files
- [x] Task 4 – Get static and media files stored on Cloudinary

## EPIC
1. #38
