### ISSUE TITLE
USER STORY: Manage posts

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/travelogue#33]
As a **Site Admin** I can **login to admin page** so that **I can create, read, update and delete posts**

## Acceptance Criteria
* Criteria 1
**Given** that I am the administrator
**When** I login to the admin panel
**Then** I have access to manage all posts

## Tasks
- [x] Task 1 – Add post model to the admin panel
- [x] Task 2 –  Add post filter
- [x] Task 3 –  Add post display list fields
- [x] Task 4 –  Add post search fields

## EPIC
1. #44
