### ISSUE TITLE
USER STORY: Manage Comments

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/travelogue#36]
As a **Site Admin** I can **login to admin page** so that **I can manage comments**

## Acceptance Criteria
* Criteria 1
**Given** that I am the administrator
**When** I login to the admin panel
**Then** I can manage comments

## Tasks
- [x] Task 1 – Add comment model to the admin panel
- [x] Task 2 –  Add comment filter
- [x] Task 3 –  Add comment display list fields
- [x] Task 4 –  Add comment search fields
- [x] Task 5 - Add actions to approve and disapprove comments

## EPIC
1. #44
