### ISSUE TITLE
USER STORY: Create an account

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/travelogue#7]
As a **Site User** I can **register to the site** so that **I can create an account to view, comment and like or unlike posts**

## Acceptance Criteria
* Criteria 1
**Given** that I am an unregistered user
**When** I am on any page
**Then** I can see a link from the navigation bar to sign up

* Criteria 2
**Given** that I see the sign-up link
**When** I click on the link
**Then** I am taken to the user registration page

* Criteria 3
**Given** that I am in the user registration page
**When** I submit valid username, email address and password
**Then** the system creates me an account and signs me in

## Tasks
- [x] Task 1 – Use Django library to develop registration process
- [x] Task 2 – Create a button in the nav bar to direct users to the registration page
- [x] Task 3 – Create registration form
- [x] Task 4 – Validate registration details
- [x] Task 5 – Remove the register button from the nav bar when users are successfully logged in

## EPIC
1. #39
