### ISSUE TITLE
USER STORY: Edit own account

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/travelogue#9]
As a **Site User** I can **edit my own profile** so that **I can update details on my profile**

## Acceptance Criteria
* Criteria 1
**Given** that I am in my account profile
**When** I want to update my details
**Then** an option is available to save my new details

* Criteria 2
**Given** that I have updated the unrestricted fields such as account name
**When** I click 'Save'
**Then** it should perform necessary validations before commit save profile

## Tasks
- [x] Task 1 – Develop process to allow users to edit profile except username
- [x] Task 2 – Create Update button to allow changes
- [x] Task 3 – Validate changes before update is allowed

## EPIC
1. #39
